# Generated by Django 5.1 on 2024-09-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_furniture_category_furniture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='furniture',
            name='material',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
